# Generated by Django 4.1.7 on 2023-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(blank=True, upload_to='photo/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
