# Generated by Django 4.1.7 on 2023-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_usercoupon_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='address',
            name='order_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50),
        ),
    ]
